frr version 8.2.2
frr defaults traditional
hostname ISP1
service integrated-vtysh-config
!
ip route 198.51.100.2/32 eth0
!
interface eth0
 ip address 198.51.100.1/30
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
router bgp 64501
 bgp router-id 1.1.1.1
 bgp log-neighbor-changes
 no bgp network import-check
 neighbor 198.51.100.2 remote-as 64512
 neighbor 198.51.100.2 description R1_BORDER
 !
 address-family ipv4 unicast
  network 1.0.0.0/8
  network 8.8.8.8/32
  neighbor 198.51.100.2 default-originate
 exit-address-family
exit
!
end
