frr version 8.2.2
frr defaults traditional
hostname ISP2
service integrated-vtysh-config
!
ip route 198.51.100.6/32 eth0
!
interface eth0
 ip address 198.51.100.5/30
exit
!
interface lo
 ip address 2.2.2.2/32
exit
!
router bgp 64502
 bgp router-id 2.2.2.2
 bgp log-neighbor-changes
 no bgp network import-check
 neighbor 198.51.100.6 remote-as 64512
 neighbor 198.51.100.6 description R2_BORDER
 !
 address-family ipv4 unicast
  network 2.0.0.0/8
  network 9.9.9.9/32
  neighbor 198.51.100.6 default-originate
 exit-address-family
exit
!
end
