frr version 8.2.2
frr defaults traditional
hostname R1
service integrated-vtysh-config
!
ip route 0.0.0.0/0 198.51.100.1
!
interface eth0
 ip address 198.51.100.2/30
exit
!
interface eth1
 ip address 192.168.100.1/30
 ip ospf area 0
exit
!
interface lo
 ip address 10.0.0.1/32
 ip ospf area 0
 ip ospf passive
exit
!
router bgp 64512
 bgp router-id 10.0.0.1
 bgp log-neighbor-changes
 no bgp network import-check
 neighbor 10.0.0.2 remote-as 64512
 neighbor 10.0.0.2 description R2_IBGP
 neighbor 10.0.0.2 update-source lo
 neighbor 10.0.0.3 remote-as 64512
 neighbor 10.0.0.3 description R3_IBGP
 neighbor 10.0.0.3 update-source lo
 neighbor 198.51.100.1 remote-as 64501
 neighbor 198.51.100.1 description ISP1
 !
 address-family ipv4 unicast
  redistribute ospf
  neighbor 10.0.0.2 route-reflector-client
  neighbor 10.0.0.2 next-hop-self
  neighbor 10.0.0.3 route-reflector-client
  neighbor 10.0.0.3 next-hop-self
  neighbor 198.51.100.1 route-map ISP1-IN in
  neighbor 198.51.100.1 route-map ISP1-OUT out
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.0.1
 default-information originate
exit
!
ip prefix-list OUR-NETS seq 5 permit 10.10.0.0/16 le 32
ip prefix-list OUR-NETS seq 10 permit 10.20.0.0/16 le 32
ip prefix-list OUR-NETS seq 15 permit 10.30.0.0/16 le 32
!
route-map ISP1-IN permit 10
 set local-preference 150
exit
!
route-map ISP1-OUT permit 10
 match ip address prefix-list OUR-NETS
exit
!
end
