frr version 8.2.2
frr defaults traditional
hostname R2
service integrated-vtysh-config
!
ip route 0.0.0.0/0 198.51.100.5 100
!
interface eth0
 ip address 198.51.100.6/30
exit
!
interface eth1
 ip address 192.168.100.5/30
 ip ospf area 0
exit
!
interface lo
 ip address 10.0.0.2/32
 ip ospf area 0
 ip ospf passive
exit
!
router bgp 64512
 bgp router-id 10.0.0.2
 bgp log-neighbor-changes
 no bgp network import-check
 neighbor 10.0.0.1 remote-as 64512
 neighbor 10.0.0.1 description R1_IBGP
 neighbor 10.0.0.1 update-source lo
 neighbor 10.0.0.3 remote-as 64512
 neighbor 10.0.0.3 description R3_IBGP
 neighbor 10.0.0.3 update-source lo
 neighbor 198.51.100.5 remote-as 64502
 neighbor 198.51.100.5 description ISP2
 !
 address-family ipv4 unicast
  redistribute ospf
  neighbor 10.0.0.1 route-reflector-client
  neighbor 10.0.0.1 next-hop-self
  neighbor 10.0.0.3 route-reflector-client
  neighbor 10.0.0.3 next-hop-self
  neighbor 198.51.100.5 route-map ISP2-IN in
  neighbor 198.51.100.5 route-map ISP2-OUT out
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.0.2
exit
!
ip prefix-list OUR-NETS seq 5 permit 10.10.0.0/16 le 32
ip prefix-list OUR-NETS seq 10 permit 10.20.0.0/16 le 32
ip prefix-list OUR-NETS seq 15 permit 10.30.0.0/16 le 32
!
route-map ISP2-IN permit 10
 set local-preference 100
exit
!
route-map ISP2-OUT permit 10
 match ip address prefix-list OUR-NETS
exit
!
end
