frr version 8.2.2
frr defaults traditional
hostname R3
service integrated-vtysh-config
!
interface dummy1
 ip address 10.30.0.1/16
 ip ospf passive
exit
!
interface eth0
 ip address 192.168.100.2/30
 ip ospf area 0
exit
!
interface eth1
 ip address 192.168.100.6/30
 ip ospf area 0
exit
!
interface eth2
 ip address 192.168.1.1/30
 ip ospf area 0
exit
!
interface eth3
 ip address 192.168.2.1/30
 ip ospf area 1
exit
!
interface lo
 ip address 10.0.0.3/32
 ip ospf area 0
 ip ospf passive
exit
!
router bgp 64512
 bgp router-id 10.0.0.3
 bgp log-neighbor-changes
 no bgp network import-check
 neighbor 10.0.0.1 remote-as 64512
 neighbor 10.0.0.1 description R1_RR_CLIENT
 neighbor 10.0.0.1 update-source lo
 neighbor 10.0.0.2 remote-as 64512
 neighbor 10.0.0.2 description R2_RR_CLIENT
 neighbor 10.0.0.2 update-source lo
 !
 address-family ipv4 unicast
  network 10.30.0.0/16
  neighbor 10.0.0.1 route-reflector-client
  neighbor 10.0.0.2 route-reflector-client
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.0.3
 area 1 range 10.30.0.0/16
exit
!
end
