frr version 8.2.2
frr defaults traditional
hostname R5
service integrated-vtysh-config
!
interface eth0
 ip address 192.168.2.2/30
 ip ospf area 1
exit
!
interface lo
 ip address 10.20.0.1/32
 ip ospf area 1
 ip ospf passive
exit
!
interface dummy1
 ip ospf area 1
 ip ospf passive
exit
!
interface dummy2
 ip ospf area 1
 ip ospf passive
exit
!
router ospf
 ospf router-id 10.20.0.1
exit
!
end
