client docker-bridge {
    ipaddr      = 172.28.0.0/24
    secret      = lab-radius-secret-2026
    require_message_authenticator = no
    nas_type    = other
    shortname   = docker-bridge
}

client gns3-lab-network {
    ipaddr      = 192.168.150.0/24
    secret      = lab-radius-secret-2026
    require_message_authenticator = no
    nas_type    = other
    shortname   = gns3-lab-network
}

client localhost {
    ipaddr  = 127.0.0.1
    secret  = testing123
    shortname = localhost
}

client gns3-ubuntu-network {
    ipaddr      = 192.168.200.0/24
    secret      = lab-radius-secret-2026
    require_message_authenticator = no
    nas_type    = other
    shortname   = gns3-ubuntu-network
}
