prefix = /opt
exec_prefix = ${prefix}
sysconfdir = /etc
localstatedir = /var
sbindir = ${exec_prefix}/sbin
logdir = /var/log/radius
raddbdir = /etc/raddb
radacctdir = ${logdir}/radacct

name = freeradius
confdir = ${raddbdir}
modconfdir = ${confdir}/mods-config
run_dir = ${localstatedir}/run/radiusd
db_dir = ${raddbdir}

prefix = /opt
panic_action = ""

max_request_time = 30
cleanup_delay = 5
max_requests = 1024

listen {
    type = auth
    ipaddr = *
    port = 1812
    virtual_server = default
    virtual_server = default
}

listen {
    type = acct
    ipaddr = *
    port = 1813
    virtual_server = default
    virtual_server = default
}

# CoA / Disconnect-Request listener (Stage 5)
listen {
    type = coa
    ipaddr = *
    port = 3799
    virtual_server = default
    virtual_server = default
}

hostname_lookups = no

log {
    destination = stdout
    colourise = yes
    file = ${logdir}/radius.log
    syslog_facility = daemon
    stripped_names = no
    auth = yes
    auth_badpass = yes
    auth_goodpass = yes
}

checkrad = ${sbindir}/checkrad

security {
    max_attributes = 200
    reject_delay = 1
    status_server = yes
}

proxy_requests = yes
$INCLUDE proxy.conf
$INCLUDE clients.conf

thread pool {
    start_servers = 5
    max_servers = 32
    min_spare_servers = 3
    max_spare_servers = 10
    max_requests_per_server = 0
}

modules {
    $INCLUDE mods-enabled/
}

instantiate {
}

policy {
    $INCLUDE policy.d/
}

$INCLUDE sites-enabled/
